unique_ids:
  assets:
    standard-page.html: JBNHV3XPBHY7SAVFPYCZQZ2MYBQAOBOH
    theme.css: 4OI5QMBG23QHPFTVSUOJTY3LOWKZO32U
  forms:
    Form1: KI3KW55ZFWI72TTRH2D2BSXIFM3Z2I67
  modules: {}
  scripts: {}
  server_modules:
    ServerModule1: '1771688387739281829335061.55237'
